### PR TITLE
Support tty

### PR DESCRIPTION
**Pull request by alok**
Patch taken from @myii in https://github.com/and3rson/flake8-colors/issues/2

### CODE REVIEW

**Comment by KTibow** [comment]
Any chance of merging @and3rson?

**Comment by and3rson** [comment]
Oh, I've totally missed one. My bad! :(

Thanks for the bump! Merging now.

**Comment by and3rson** [comment]
I'll redeploy to pypi later today.

**Comment by KTibow** [comment]
By the way, is there any reason you stopped watching this repo?

**Comment by and3rson** [comment]
Most likely I was very short of time & then lost track of things. I'm happy to add maintainers / transfer repo somewhere if anyone is open to maintaining it :)

**Comment by KTibow** [comment]
Now that this is merged, any possibility of #2 being put in?

**Pull request merged**
